name: Update EPG XML

on:
  schedule:
    - cron: "0 * * * *"  # Pokreće se svakih sat vremena
  workflow_dispatch: # Ručno pokretanje

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download latest EPG XML
        run: wget -O epg.xml "http://sehara.eu/epgshare/epg.xml"

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add epg.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update epg.xml"
          git push
