name: Update EPG

on:
  schedule:
    - cron: "0 */6 * * *"  # Pokreće se svakih 6 sati
  workflow_dispatch:  # Omogućava ručno pokretanje

jobs:
  update_epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download new EPG file
        run: wget -O epg.xml "https://epgshare01.online/epgshare01/epg.xml"

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add epg.xml
          git commit -m "Automatsko ažuriranje EPG-a" || echo "Nema promjena za commit"
          git push

