name: Update EPG XML

on:
  schedule:
    - cron: "*/5 * * * *"  # Pokreće se svakih 5 minuta
  workflow_dispatch:  # Ručno pokretanje iz GitHub Actions

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download latest EPG XML
        run: wget -O epg.xml "https://epgshare01.online/epgshare01/"

      - name: Compress EPG XML
        run: gzip -c epg.xml > epg.xml.gz

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add epg.xml.gz
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update epg.xml.gz"
          git push
